### PR TITLE
add configurable API key to load script

### PR DESCRIPTION
**Pull request by noinfo**
Will add an API key that can be configured in the main _config.yml to
the script loader

### CODE REVIEW

**Comment by noinfo** [comment]
Updated to take care of the marker code that got lost and updated version number to 1.1.1 for npm to notice the change.

**Comment by malenkiki** [comment]
This must be merge as soon as possible, key is mandatory.

**Comment by the-simian** [comment]
Thanks for the reminder @malenkiki , I wrote this back when it wasn't mandatory, but you're right it is now

**Comment by the-simian** [comment]
@malenkiki  @noinfo ok i published

**Pull request merged**
